// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn4cFyHBwbKynWdCdabVmG_6x8wmQFXMM',
    appId: '1:352903375107:web:cae4793f267336e356a136',
    messagingSenderId: '352903375107',
    projectId: 'thewatcher-87d35',
    authDomain: 'thewatcher-87d35.firebaseapp.com',
    storageBucket: 'thewatcher-87d35.appspot.com',
    measurementId: 'G-R3NND52J9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6og93Lb1mcIl4F-GHn5KLO6ejNNg9mg',
    appId: '1:352903375107:android:3f186f9543da098e56a136',
    messagingSenderId: '352903375107',
    projectId: 'thewatcher-87d35',
    storageBucket: 'thewatcher-87d35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DcBNME_iVeFdo8GJs9ujlJwXoMDDnsk',
    appId: '1:352903375107:ios:e31c112ea9cf41a256a136',
    messagingSenderId: '352903375107',
    projectId: 'thewatcher-87d35',
    storageBucket: 'thewatcher-87d35.appspot.com',
    iosClientId: '352903375107-6ttf1ghgkavcssq4lkko7c50iq0j3lma.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1DcBNME_iVeFdo8GJs9ujlJwXoMDDnsk',
    appId: '1:352903375107:ios:e31c112ea9cf41a256a136',
    messagingSenderId: '352903375107',
    projectId: 'thewatcher-87d35',
    storageBucket: 'thewatcher-87d35.appspot.com',
    iosClientId: '352903375107-6ttf1ghgkavcssq4lkko7c50iq0j3lma.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWatcher',
  );
}
